### ISSUE TITLE
FAQ page design

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#175]
https://cds2019-d4673.firebaseapp.com/faqs/

Do you want something better than this?

**Comment by argyleink** [comment]
was researching to see if FAQ had an agreed upon semantic structure, found this from the W3C https://www.w3.org/TR/wai-aria-practices/examples/disclosure/disclosure-faq.html

thoughts on using the "disclosure design pattern" for our FAQ section? it'd change a bit of what I design, since in this W3C suggestion, details are hidden until revealed, leaving me to design with a bunch of titles. 

i feel like regardless of hiding details or not, i do like `<dl>` for the markup structure.

**aside / bug:**
i'm interested why every heading is an h1? i mean, sections and articles can reset headings, but curious if there's something for me to learn here or it's just currently reflecting the speed at which the page was built? 

![faq-h1](https://user-images.githubusercontent.com/1134620/62480834-b9e6c780-b765-11e9-98be-bdba9853babc.gif)

**Comment by jakearchibald** [comment]
> thoughts on using the "disclosure design pattern" for our FAQ section?

No strong feelings. Alternatively we could have a table of contents (in page links) at the top.

> i feel like regardless of hiding details or not, i do like <dl> for the markup structure.

If we are hiding the details, we should use [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details).

If I can't decide between `<dl>` and heading-content, I tend to go for heading-content, as it'll show up for screen reader users when they scan for headings. I usually only use `<dl>` for key-value or definition-description.

> i'm interested why every heading is an h1?

If you're writing an FAQ like https://github.com/GoogleChrome/devsummit/blob/master/src/faqs/items/01-general/01-dates-location.md, but it needs to include a heading, which heading level will you use? This is especially tricky with content that appears in multiple places.

The section/heading model solves this problem by being modular. Unfortunately it isn't well supported by browsers, so we may have to add a little JS (or a build step) to fix it.

**Comment by argyleink** [comment]
https://xd.adobe.com/view/d4b1e5c5-5854-45e9-b2e9-0dd4f3066b94-81e2/

thoughts?

**Comment by argyleink** [comment]
minor design updates to this page can be found at the XD link 👍 
- nav bar updates
- added stream module

**Comment by jakearchibald** [comment]
Ohh very nice!

**Comment by jakearchibald** [comment]
Next step: https://github.com/GoogleChrome/devsummit/issues/253
