### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#210]
@argyleink dunno if you want to do anything special here?

**Comment by surma** [comment]
Something... _delightful_?

**Comment by argyleink** [comment]
oh yes, leave this to me

**Comment by argyleink** [comment]
do we have access to the downosaur code? curious if that's a web component or something we can plop onto a 404

**Comment by argyleink** [comment]
#### 404 cacti desert
Mostly just svg, could have a tumbling dust thingy if we want

#### bouncing screensaver 404
this https://www.youtube.com/watch?v=rAjfE9JHO_I, but with 404 in google sans bouncing around the viewport

![IMG_20190806_095343](https://user-images.githubusercontent.com/1134620/62559745-5c6b7d00-b830-11e9-8744-1455c2fbedd1.jpg)

**Comment by jakearchibald** [comment]
I like the bouncing 404 idea. What if the animation started so the 404 block was on course to hit the exact in like 15 seconds, but just before it hits the corner it swerves and misses.

**Comment by argyleink** [comment]
thoughts?

**note:** 
- comps here dont show the fold line, [see XD](https://xd.adobe.com/view/d4b1e5c5-5854-45e9-b2e9-0dd4f3066b94-81e2/screen/0263212a-c2f2-4e46-ba9c-6ce3c01b7560/Largest-404) for where that should be
- comps (since no fold line) have about 10px of "peaking" happening from the content below the fold
- thoughts on the 404 having a surprised face in the middle? lol, any PC flags here my naive self didnt notice? 

##### mobile
![Go Phone – 404](https://user-images.githubusercontent.com/1134620/62969802-ec766d00-bdc2-11e9-92f6-b0372f0067bf.png)

##### desktop
![Largest - 404](https://user-images.githubusercontent.com/1134620/62969803-ec766d00-bdc2-11e9-98bd-cb1731bce439.png)

**Comment by jakearchibald** [comment]
This seems good to me

**Comment by surma** [comment]
I’ll take care of this today

**Comment by surma** [comment]
Took a stab at this, and it hilariously complicated due to our setup. I’ll move this one to post-launch.

**Comment by argyleink** [comment]
v1 could also be static (centered in viewport), with animated as "nice to have"?
i... am also dying to hear how the setup made this complicated!

**Comment by surma** [comment]
CDS team wants this, so Imma find a hacky solution to the technical problems.

**Comment by surma** [comment]
CDS team wants this, so Imma find a hacky solution to the technical problems.

> thoughts on the 404 having a surprised face in the middle? lol, any PC flags here my naive self didnt notice?

By the powers vested in me being German, I approve of Umlauts.
