### ISSUE TITLE
Sessions collection page design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#225]
consider a grouped listview

**Comment by jakearchibald** [comment]
Does it make sense to have a sessions collection page? Given that all sessions are within the schedule, isn't it redundant?

**Comment by jakearchibald** [comment]
Ah, but the schedule page is redundant after the event (and there may be a period where we don't have a schedule, but do have sessions).

So would our plan be:

**Before the event:** If we have a schedule, use that instead of a sessions index.

**After the event:** Use the session index instead of the schedule.

**Comment by vschupmann** [comment]
That is a brilliant idea to have a post-event session index.
