### ISSUE TITLE
Forum module design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#229]
probably will look like this

![Screen Shot 2019-08-08 at 10 38 15 AM](https://user-images.githubusercontent.com/1134620/62725415-f4e93500-b9c9-11e9-802c-bd6223906286.png)

**Comment by carolrivero** [comment]
I'm not sure I understand. We don't need to break down the demos in time slots because they will be running all day. We only need to provide the duration when the sandbox will be open to attendees (As an example Day 1 from 9AM to 4PM, etc). A list of the demos will be helpful though so attendees have a preview of what they can check out in the space. One TBD is the office hours - I don't have a sense of what those. Thanks.

**Comment by argyleink** [comment]
sounds like we're aligned then carol! the "forum module" was the "expo hall hours" widget on the right. the left is a schedule, i'm not expecting to schedule out the forum.
