### ISSUE TITLE
Extra day in schedule with adjusted timezone

### ISSUE THREAD

**Issue by oslego** [GoogleChrome/devsummit#297]
![cds-schedule-extraday](https://user-images.githubusercontent.com/63899/65590446-1d81ba00-df8b-11e9-9249-262a965a20a3.jpg)

This potential issue was highlighted in [#145 (comment)](https://github.com/GoogleChrome/devsummit/issues/145#issuecomment-531080828). Adjusting the timezone for Central European Time, ~aside from showing incorrect times (see #296)~, added an extra third day to the event. 

This was a source of confusion for a while, making me consider whether there is an extra event day and I needed to adjust potential travel plans.

**Update**
Since I got extra confused with this and #296, may I offer a suggestion:
Instead of a toggle to switch times, what do you think of a checkbox to add another row to the time field of every session with the adjusted time? 

When spanning days, perhaps the solution used by airline websites to show 12:50am (+1 day) or (-1 day) can help dispel confusion, especially seeing the session times side-by-side.

Essentially, the underlying feature request is to keep the sessions grouped by event day instead of calendar day when they happen to occur in respective time zones.

**Comment by surma** [comment]
Yeah, I see where you are coming from. And as you have found out, we are aware of this potential confusion as well.

We settled on this because it's "technically correct". If we left the days as "conference days" and only changed the times, people could also get confused. My talk, for example, is on day 1 at 3:10pm. In UTC+2 that means it 12:10am, but listing it as "Day 1 12:10am" is wrong. 

I think if you are attending, you should not be looking at the conference schedule in your home time zone. If you are watching from home, I think the current view is more helpful.

> When spanning days, perhaps the solution used by airline websites to show 12:50am (+1 day) or (-1 day) can help dispel confusion, especially seeing the session times side-by-side.

I like this idea, but as always, screen estate is sparse (especially on feature phones!). I'm happy to let @argyleink take a stab at this from the design side of things and see if we can make it work without things getting too cramped or confusing.

**Comment by jakearchibald** [comment]
I guess it comes down to what we think is better:

Nov 12th - 12:15am
vs
Nov 11th - 12:15am + 1 day

The latter seems more confusing to me.

**Comment by jakearchibald** [comment]
> This was a source of confusion for a while, making me consider whether there is an extra event day and I needed to adjust potential travel plans.

**Venue time** - The times things will happen if you're attending the event.
**Your time** - The times things will happen in your current timezone.

If you're planning to attend, then "your time" isn't really useful, because it doesn't reflect the times things will happen for you when the event starts, since you're planning to travel halfway around the world.

It seems like we didn't communicate this in the UI. Can you describe why you used the "your time" view when you're planning to attend?

**Comment by oslego** [comment]
> It seems like we didn't communicate this in the UI. Can you describe why you used the "your time" view when you're planning to attend?

I used the toggle because it was there and wanted to check it out :) It seemed like a cool idea.

I don't know yet if I can attend (registration response hasn't arrived yet), but as I was playing with the website I got concerned that I have to consider alternative plans for an extra event day in case I do end up attending.

> If you're planning to watch the livestream from your current timezone, then "venue time" isn't really useful, because it doesn't tell you when to watch the session.

Agreed. Perhaps it's just ingrained user expectation that, when viewing an event schedule, I expected sessions grouped by event day (and I would organise my time around that) instead of sessions proactively organised by time for me. Which works great, until an extra day shows up in the schedule.

It's clear to me now how the toggle works.

**Comment by oslego** [comment]
Thanks for taking an interest in explaining the reasoning behind the approach. 
Timezones are hard. User expectations more so.

Since there's no obvious UI fix that itself wouldn't add to the confusion, I will close this issue. 

If more people raise the issue, feel free to reopen and address.
